# Generated by Django 5.0.6 on 2024-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.TextField(max_length=1000),
        ),
    ]
